/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as AuthImport } from './routes/_auth'
import { Route as AuthIndexImport } from './routes/_auth/index'
import { Route as AuthTransaccionesPresupuestoImport } from './routes/_auth/transacciones/presupuesto'
import { Route as AuthTransaccionesFacturasImport } from './routes/_auth/transacciones/facturas'
import { Route as AuthTransaccionesCierreImport } from './routes/_auth/transacciones/cierre'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const AuthIndexRoute = AuthIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)

const AuthTransaccionesPresupuestoRoute =
  AuthTransaccionesPresupuestoImport.update({
    id: '/transacciones/presupuesto',
    path: '/transacciones/presupuesto',
    getParentRoute: () => AuthRoute,
  } as any)

const AuthTransaccionesFacturasRoute = AuthTransaccionesFacturasImport.update({
  id: '/transacciones/facturas',
  path: '/transacciones/facturas',
  getParentRoute: () => AuthRoute,
} as any)

const AuthTransaccionesCierreRoute = AuthTransaccionesCierreImport.update({
  id: '/transacciones/cierre',
  path: '/transacciones/cierre',
  getParentRoute: () => AuthRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexImport
      parentRoute: typeof AuthImport
    }
    '/_auth/transacciones/cierre': {
      id: '/_auth/transacciones/cierre'
      path: '/transacciones/cierre'
      fullPath: '/transacciones/cierre'
      preLoaderRoute: typeof AuthTransaccionesCierreImport
      parentRoute: typeof AuthImport
    }
    '/_auth/transacciones/facturas': {
      id: '/_auth/transacciones/facturas'
      path: '/transacciones/facturas'
      fullPath: '/transacciones/facturas'
      preLoaderRoute: typeof AuthTransaccionesFacturasImport
      parentRoute: typeof AuthImport
    }
    '/_auth/transacciones/presupuesto': {
      id: '/_auth/transacciones/presupuesto'
      path: '/transacciones/presupuesto'
      fullPath: '/transacciones/presupuesto'
      preLoaderRoute: typeof AuthTransaccionesPresupuestoImport
      parentRoute: typeof AuthImport
    }
  }
}

// Create and export the route tree

interface AuthRouteChildren {
  AuthIndexRoute: typeof AuthIndexRoute
  AuthTransaccionesCierreRoute: typeof AuthTransaccionesCierreRoute
  AuthTransaccionesFacturasRoute: typeof AuthTransaccionesFacturasRoute
  AuthTransaccionesPresupuestoRoute: typeof AuthTransaccionesPresupuestoRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthIndexRoute: AuthIndexRoute,
  AuthTransaccionesCierreRoute: AuthTransaccionesCierreRoute,
  AuthTransaccionesFacturasRoute: AuthTransaccionesFacturasRoute,
  AuthTransaccionesPresupuestoRoute: AuthTransaccionesPresupuestoRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/': typeof AuthIndexRoute
  '/transacciones/cierre': typeof AuthTransaccionesCierreRoute
  '/transacciones/facturas': typeof AuthTransaccionesFacturasRoute
  '/transacciones/presupuesto': typeof AuthTransaccionesPresupuestoRoute
}

export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AuthIndexRoute
  '/transacciones/cierre': typeof AuthTransaccionesCierreRoute
  '/transacciones/facturas': typeof AuthTransaccionesFacturasRoute
  '/transacciones/presupuesto': typeof AuthTransaccionesPresupuestoRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/transacciones/cierre': typeof AuthTransaccionesCierreRoute
  '/_auth/transacciones/facturas': typeof AuthTransaccionesFacturasRoute
  '/_auth/transacciones/presupuesto': typeof AuthTransaccionesPresupuestoRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/login'
    | '/'
    | '/transacciones/cierre'
    | '/transacciones/facturas'
    | '/transacciones/presupuesto'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/transacciones/cierre'
    | '/transacciones/facturas'
    | '/transacciones/presupuesto'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/_auth/'
    | '/_auth/transacciones/cierre'
    | '/_auth/transacciones/facturas'
    | '/_auth/transacciones/presupuesto'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_auth",
        "/login"
      ]
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/",
        "/_auth/transacciones/cierre",
        "/_auth/transacciones/facturas",
        "/_auth/transacciones/presupuesto"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_auth/": {
      "filePath": "_auth/index.tsx",
      "parent": "/_auth"
    },
    "/_auth/transacciones/cierre": {
      "filePath": "_auth/transacciones/cierre.tsx",
      "parent": "/_auth"
    },
    "/_auth/transacciones/facturas": {
      "filePath": "_auth/transacciones/facturas.tsx",
      "parent": "/_auth"
    },
    "/_auth/transacciones/presupuesto": {
      "filePath": "_auth/transacciones/presupuesto.tsx",
      "parent": "/_auth"
    }
  }
}
ROUTE_MANIFEST_END */
